apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      managed-by: kustomize
    includeSelectors: true

configMapGenerator:
  - name: app-settings
    literals:
      - LOG_LEVEL=info
      - APP_GREETING=hello-from-kustomize
