apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rox
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/pv-rox-data
