apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rox
  namespace: training
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
  volumeName: pv-rox
