apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
  namespace: training
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
