apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-pvc
  namespace: training
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: lab-pv
