apiVersion: v1
kind: Service
metadata:
  name: httpd-headless
  namespace: training
spec:
  clusterIP: None
  selector:
    app: httpd
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
