apiVersion: v1
kind: Pod
metadata:
  name: log-single
  namespace: training
  labels:
    app: log-single
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
