apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-backup
  hostPath:
    path: /tmp/backup-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: training
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-backup
  resources:
    requests:
      storage: 1Gi
