apiVersion: v1
kind: Pod
metadata:
  name: catalog
  namespace: ts92
  labels:
    app: catalog
spec:
  containers:
    - name: web
      image: nginx:1.99-doesnotexist
      ports:
        - containerPort: 80
