apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: training
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - webapp.training.local
      secretName: webapp-tls-secret
  rules:
    - host: webapp.training.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp-svc
                port:
                  number: 80
