apiVersion: v1
kind: Service
metadata:
  name: hello-np
  namespace: net41
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30411
    protocol: TCP
