apiVersion: v1
kind: Pod
metadata:
  name: api-explorer-pod
  namespace: training
spec:
  serviceAccountName: api-explorer
  containers:
    - name: curl
      image: curlimages/curl:latest
      command:
        - sleep
        - "3600"
