apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: pv-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
