apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: kdemo
  labels:
    app: cache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.1
        ports:
        - containerPort: 80
