apiVersion: v1
kind: Pod
metadata:
  name: rbac-test-pod
  namespace: rbac-lab
spec:
  serviceAccountName: pod-reader
  containers:
    - name: kubectl
      image: alpine/k8s:1.35.1
      command:
        - sleep
        - "3600"
