apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
  namespace: training
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "echo Username=$DB_USER Password=$DB_PASS && sleep 3600"]
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
  restartPolicy: Never
