apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-volume
  namespace: training
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "cat /etc/secrets/username && echo '' && cat /etc/secrets/password && sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret
  restartPolicy: Never
