apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: ts97
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
