apiVersion: v1
kind: Pod
metadata:
  name: taint-pending-pod
  namespace: training
spec:
  containers:
    - name: app
      image: nginx:1.25
      resources:
        requests:
          memory: 32Mi
          cpu: 50m
