apiVersion: v1
kind: Pod
metadata:
  name: pod-node-affinity
  namespace: training
  labels:
    app: affinity-test
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 80
          preference:
            matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
                  - nvme
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
