apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: q63
spec:
  limits:
  - type: Container
    min:
      cpu: 50m
      memory: 64Mi
    max:
      cpu: 500m
      memory: 512Mi
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
